---
title: "Week 02 - Data Exploration"
author: "Luca Cerone"
output: 
html_document:
code_folding: hide
---

```{r setup}
suppressMessages({
  knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, error = FALSE)
  library(readr)
  library(parallel)
  library(doParallel)
  library(iterators)
  library(tm)
  library(ngram)
  library(dplyr)
  library(data.table)
  library(stringr)
})
```

### Importing all the files

```{r}
nwords <- function(s) {
  force(s)
  m <- str_match_all( s, "\\S+" )  # Sequences of non-spaces
  length(m[[1]])
}
```

```{r}
blogs <- readLines("../data/en_US_cleaned/en_US.blogs_cleaned.txt")
blogs <- gsub("<unknown>", "", blogs)

news <- readLines("../data/en_US_cleaned/en_US.news_cleaned.txt")
news <- gsub("<unknown>", "", news)

twitter <- readLines("../data/en_US_cleaned/en_US.twitter_cleaned.txt")
twitter <- gsub("<unknown>", "", twitter)

all <- c(blogs, news, twitter)
lall <- split(all, floor((seq_along(all)-1)/25000))

rm(all)
rm(blogs)
rm(news)
rm(twitter)
gc()
```

```{r}
get_phrasetable <- function(txt, n, min_freq = 1, max_freq = Inf) {
  gc()
  txt <- paste(txt, collapse = "\n")
  ng <- ngram(txt, n = n+1, sep = " ")
  rm(txt)
  gc()
  pt <- get.phrasetable(ng)
  rm(ng)
  gc()
  
  rexp <- paste0("^(", paste0(rep("[a-z]+",n), collapse = "\\s"), ")\\s([a-z]+)\\s+$")
  X <- str_match(pt$ngrams, rexp)
  # Search for ngram
  pt$ngrams <- NULL
  pt$ngram <-  X[,2]
  pt$next_word <-  X[,3]
  rm(X)
  gc()
  pt <- as.data.table(pt)
  gc()
  pt[!is.na(ngram), .(ngram, next_word, freq)][freq >= min_freq][freq <= max_freq]
}
```

### Build 2-grams and next word table

```{r}
lall <- lapply(lall, function(x) {force(x); x[sapply(x,nwords, simplify = T, USE.NAMES = F) > 2]})
gc()
pt <- get_phrasetable(lall[[1]],2, min_freq = 2)
gc()
for ( i in seq(2, length(lall)) ) {
  print(i)
  cpt <- get_phrasetable(lall[[i]],2, min_freq = 2)
  pt <- rbind(pt, cpt)
  rm(cpt)
  gc()
  pt <- pt[, .(freq = sum(freq)), by = c("ngram", "next_word")]
  gc()
}

write_tsv(pt, "../data/en_US_ngrams/2ngrams_full.tsv")

pt <- pt[order(-freq), head(.SD,1), by = "ngram"]
write_tsv(pt, "../data/en_US_ngrams/2ngrams_predictions.tsv")

##
pt <- get_phrasetable(lall[[1]],2, min_freq = 1, max_freq=1 )
gc()
for ( i in seq(2, length(lall)) ) {
  print(i)
  cpt <- get_phrasetable(lall[[i]],2, min_freq = 1, max_freq=1)
  pt <- rbind(pt, cpt)
  rm(cpt)
  gc()
  pt <- pt[, .(freq = sum(freq)), by = c("ngram", "next_word")]
  gc()
}

write_tsv(pt, "../data/en_US_ngrams/2ngrams_full.tsv", append = T)

pt <- pt[order(-freq), head(.SD,1), by = "ngram"]
write_tsv(pt, "../data/en_US_ngrams/2ngrams_predictions.tsv", append = T)
```

### Build 3-grams and next word table

```{r}
lall <- lapply(lall, function(x) {force(x); x[sapply(x,nwords, simplify = T, USE.NAMES = F) > 3]})
gc()
pt <- get_phrasetable(lall[[1]],3, min_freq = 2)
gc()
for ( i in seq(2, length(lall)) ) {
  print(i)
  cpt <- get_phrasetable(lall[[i]],3, min_freq = 2)
  pt <- rbind(pt, cpt)
  rm(cpt)
  gc()
  pt <- pt[, .(freq = sum(freq)), by = c("ngram", "next_word")]
  gc()
}

write_tsv(pt, "../data/en_US_ngrams/3ngrams_full.tsv")

pt <- pt[order(-freq), head(.SD,1), by = "ngram"]
write_tsv(pt, "../data/en_US_ngrams/3ngrams_predictions.tsv")
```

### Build 4-grams and next word table

```{r}
lall <- lapply(lall, function(x) {force(x); x[sapply(x,nwords, simplify = T, USE.NAMES = F) > 4]})
gc()
pt <- get_phrasetable(lall[[1]],4, min_freq = 2)
gc()
for ( i in seq(2, length(lall)) ) {
  print(i)
  cpt <- get_phrasetable(lall[[i]],4, min_freq = 2)
  pt <- rbind(pt, cpt)
  rm(cpt)
  gc()
  pt <- pt[, .(freq = sum(freq)), by = c("ngram", "next_word")]
  gc()
}

write_tsv(pt, "../data/en_US_ngrams/4ngrams_full.tsv")

pt <- pt[order(-freq), head(.SD,1), by = "ngram"]
write_tsv(pt, "../data/en_US_ngrams/4ngrams_predictions.tsv")
```
